server:
  port: 8888
spring:
  application:
    name: ZUUL
zuul:
  routes:
    USER:
      path: /USER
      serviceId: USER
  SendErrorFilter:
    error:
      disable: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka